### ISSUE TITLE
Add app-specific instructions to documentation.

### ISSUE THREAD

**Issue by CherryKitten** [CherryKitten/CharjaBox#3]
# What is this Issue asking for?

In the directory /docs/applications/ there should be a small documentation page about every Application that can be installed via CharjaBox.

This should be possible to do without any actual knowledge about this project. Knowledge about the specific Application (best case in combination with docker) should be enough to contribute.

# This should include:

- Link to original website of Application
- One line description of the Application
- First steps that should be done after installing the application
- Basic information about how to configure the Application
- Important things to consider (Example: A Media player needing specific file structures)

# The following apps still need documentation:

- Firefly III
- Heimdall
- Portainer

**Comment by pieceofeden** [comment]
I would like to take this up.

**Comment by CherryKitten** [comment]
Removed Plex from ToDo-List.

**Comment by CherryKitten** [comment]
Closed in favor of using one issue per app.
